### PR TITLE
181840500 Migrate CDN Images

### PR DESCRIPTION
**Pull request by PotatoParser**
## What is the new behavior?

- Increased ESLint code line rule to 150 (to accommodate image changes)
- Migrated images to local assets folder

## What is the previous behavior?

- Images are fetched in JS through a CDN.

## Why the change?

- Prepare for front-end update

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

 

## Pull request type
Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### CODE REVIEW

**Review by justincheng101 — APPROVED** [review]
LGTM!

**Review by debbieyuen — APPROVED** [review]
looks good :)

**Review by Ethan-bradley — APPROVED** [review]
Looks good to me!

**Comment by PotatoParser** [comment]
Front end redesign removes this necessity

**Pull request closed without merging**
